#include <iostream.h>
using namespace std;
//whit for
/*void main(){
    for(int i = 50; i >= 0; i-=3) {
      cout <<i<<"\n"
    }
    return 0;
}*/
//whit while
/*void main(){
  int i = 50;
  while (i>=0)
  {
    cout<<i<<endl,
    i-=3
  }
  return 0;
}*/
//whit do while
void main(){
  int i = 50
  do
  {
    cout<<i<<endl;
    i-=3
  } while (i >=0);
  return 0;
}
